project:
  type: website
  output-dir: docs

website:
  title: "Kening Jiang"
  navbar:
   left:
     - href: index.qmd
       text: Home
     - href: about.qmd
       text: About
     - href: analysis.qmd
       text: Example analysis

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full



